[package]
name = "raft-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.34", features = ["full"] }
tonic = "0.10"
prost = "0.12"
rand = "0.8"
clap = { version = "4.4", features = ["derive"] }

[build-dependencies]
tonic-build = "0.10"
